# Generated by Django 4.0.4 on 2022-07-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address',
        ),
        migrations.AlterField(
            model_name='addresses',
            name='default',
            field=models.BooleanField(blank=True, default=False, verbose_name='Default Address'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='delivery_instructions',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='zipcode',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
