# Generated by Django 4.0.4 on 2022-07-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_addresses_address_alter_addresses_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
    ]
