# Generated by Django 4.0.4 on 2022-06-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='car_name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
