# Generated by Django 4.0.4 on 2022-07-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizes',
            name='size',
            field=models.CharField(choices=[('EU16', 8.1), ('EU17', 9), ('EU18', 9.8), ('EU19', 10.6), ('EU20', 11.5), ('EU21', 12.3), ('EU22', 12.8), ('EU23', 13.2), ('EU23.5', 13.6), ('EU24', 14), ('EU25', 14.5), ('EU25.5', 14.9), ('EU26', 15.3), ('EU26.5', 15.7), ('EU27', 16.1), ('EU28', 16.6), ('EU28.5', 17), ('EU29', 17.4), ('EU30', 17.8), ('EU30.5', 18.3), ('EU31', 18.7), ('EU31.5', 19.1), ('EU32', 19.5), ('EU33', 20), ('EU33.5', 20.4), ('EU34', 20.8), ('EU35', 21.2)], help_text='Sizes are in CM. 0-3 y/o (EU16-EU28), 4-7 y/o (EU28-EU35)', max_length=255, verbose_name='Subproduct Size'),
        ),
    ]
