# Generated by Django 4.0.4 on 2022-07-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoptions',
            name='delivery_method',
            field=models.CharField(choices=[('SP', 'Store Pick-Up'), ('HD', 'Home Delivery')], help_text='Required', max_length=255, null=True, verbose_name='delivery_method'),
        ),
    ]
