# Generated by Django 4.0.4 on 2022-07-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_status',
            field=models.BooleanField(default=False, verbose_name='Payment Status'),
        ),
    ]
