# Generated by Django 4.0.4 on 2022-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_billing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False, null=True, verbose_name='Delivery Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_processing',
            field=models.BooleanField(default=False, null=True, verbose_name='Processing Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_returned',
            field=models.BooleanField(default=False, null=True, verbose_name='Return Status'),
        ),
    ]
